version: '3.7'

services:

  front-end:
    build: front-end
    ports:
      - 3000:3000
    depends_on:
      - back-end
      - nginx

  back-end:
    build: back-end
    ports:
      - 8080:8080
    depends_on:
      - nginx

  nginx:
    build: nginx
    ports:
      - 80:80